org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-25.0.2

# Fabric Properties
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Fabric API
fabric_api_version=0.136.1+1.21.8
modmenu_version=13.0.1

# Mod Properties
mod_version=1.0
maven_group=kesslercascade.rdpmouse
archives_base_name=MrRdpFix-Fabric-1.21.8-byMr712-v1.0
